services:
  db:
    image: postgres:15
    container_name: virtual_fitting_db
    restart: always
    env_file:
      - .env
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  backend:
    build: .
    container_name: virtual_fitting_backend
    restart: always
    env_file:
      - .env
    depends_on:
      - db
    ports:
      - "8000:8000"
    volumes:
      - ./storage:/app/storage
      - ./ai_server/dummy:/app/shared/dummy

  ai_server:
    build:
      context: ./ai_server
      dockerfile: Dockerfile
    container_name: virtual_fitting_ai
    ports:
      - "9002:9002"
    volumes:
      - ./ai_server/dummy:/app/shared/dummy
      # 임시 결과물을 저장할 워크스페이스 볼륨 추가
      - ./storage/ai_workspace:/app/temp_workspace
      # IDM-VTON 모델 다운로드 캐시 볼륨
      - ./ai_server/models_cache:/app/shared/models_cache
    environment:
      - PYTHONUNBUFFERED=1
      - AI_MODE=prod # 모드 설정 (prod: 더미 고속 반환 / prod: 실제 AI 모델 연산 및 GPU 활성화)
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1 # 1개의 GPU 할당 (또는 'all')
              capabilities: [gpu, utility, compute]
    restart: unless-stopped

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: virtual_fitting_frontend
    restart: always
    ports:
      - "1010:80"
    volumes:
      - ./ai_server/dummy:/usr/share/nginx/html/static:ro
    depends_on:
      - backend
      - ai_server

volumes:
  postgres_data:
